### ISSUE TITLE
Use native modulo arithmetic operators when normalising degrees

### ISSUE THREAD

**Issue by joker314** [PullJosh/scratch-js#1]
The current degree-normalisation algorithm

https://github.com/PullJosh/scratch-js/blob/b67ebe1ca487f69c9a9fefc97f8bebccb6fe58b9/scratch-js/Sprite.js#L68-L69

Has the potential to enter into an Infinite loop. The Scratch programming language exposes the value `Infinity`. Observe that decrementing it by a finite value (like 360), does not change it's value. Therefore, the loop is infinite.

This does not match the behaviour of the Scratch programming language, and so intuitive in my opinion (especially since it can cause a crash in browsers).

Hence, I propose to use the native implementation of modulo arithmetic. This has the additional positive side-effect of making the code more optimisation and efficient.

The proposed code replacement is placed below:
```javascript
((deg - 180) % 360) + 180
```
This is functionally equivalent to your current code for finite values. Both appear to be functionally equivalent to the [Scratch 2.0 implementation](https://github.com/LLK/scratch-flash/blob/646523e6846ad0dd993213a38b46fe2ea511d026/src/scratch/ScratchSprite.as#L226-L231).

Note that Scratch behaviour is to preserve current direction if a non-finite value is provided as a direction. **Neither implementation is doing this**, but they could with a simple `if` statement. Newer versions of JavaScript have a `Number.isFinite` (ES6, not supported in IE or Opera Mini). The codebase already uses ES6, so using this shouldn't be a problem and is perhaps the most readable solution.

Nice project btw!

**Comment by PullJosh** [comment]
Yes, this is absolutely the correct solution. I couldn't remember the formula so I took the lazy way. Thanks for the correction!

**Comment by joker314** [comment]
Hmm, could you provide an example of a negative number which doesn't work?

**Comment by PullJosh** [comment]
Oh, you're right! It works indeed! My problem was that I was applying your formula to Scratch's degree system rather than the regular math one. I've already got methods to do the conversion between Scratch and regular, so that shouldn't be any issue.
