### ISSUE TITLE
GUI design

### ISSUE THREAD

**Issue by micahlt** [PullJosh/scratch-js#16]
I'm better at HTML/CSS than I am at Javascript, so I'm considering starting a GUI for ScratchJS.  I was wondering 1) if work on this should even start this early and 2) if it should be designed like an actual code editor or similar to Scratch.  Feedback would be appreciated!

**Comment by PullJosh** [comment]
Creating themes and players sounds like an awesome idea, but you're probably right that it shouldn't start this early. The core parts of scratch-js are still changing quite a bit and will probably shift out from under your feet. 😬

**Comment by micahlt** [comment]
@PullJosh I suspected as much! 😄 I’m going to just develop the ascetic aspects of it (just the HTML and CSS) and we can add the actual functionality once the core parts are nailed down.

**Comment by YOYITsM3M8** [comment]
yo can i help with gui design? i has replit https
://repl.co/@retronbv

**Comment by micahlt** [comment]
@YOYITsM3M8 I’m not sure it’s necessary, seeing as there’s not really active GUI development going on, and I’ve developed a pretty good starter.  On the other hand, it’s up to @PullJosh.

**Comment by YOYITsM3M8** [comment]
oh ok.

**Comment by PullJosh** [comment]
I think GUI design is going to be something that scratch-js isn't going concern itself with. Each user of scratch-js can design their own webpage. The example project doesn't need to be particularly designed, because that isn't its purpose.
