### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by micahlt** [PullJosh/scratch-js#17]
Is there some form of documentation in progress offline or has that not yet begun?  The functions seem fairly straightforward, but a documentation would also be helpful.  If necessary, I can start detailing them (kind of like how blocks are documented on the Scratch Wiki).

**Comment by PullJosh** [comment]
Documentation would be awesome! (There isn't any offline.) If you want to help, documentation could go in the [Github wiki](https://github.com/PullJosh/scratch-js/wiki). If you're feeling ambitious, go for it. 😄

**Comment by micahlt** [comment]
@PullJosh That just redirects to the code page.  Only the repository owner and contributors can edit the Wiki.  🙁

**Comment by PullJosh** [comment]
Hmm... I just added the first page. Does it work now?

**Comment by micahlt** [comment]
@PullJosh I can see the page, but I can’t edit.  I’ll just write the docs in Markdown offline, and then you can add them to the wiki.  👍

**Comment by micahlt** [comment]
@PullJosh I started off the documentation.  You should probably check it out and make sure everything’s accurate before it goes on the Wiki.  😄 [Google Drive link](https://drive.google.com/file/d/1r77xijQmDHVlCRInvwKylLzPATVFh0-A/view?usp=sharing)

**Comment by PullJosh** [comment]
@micahlt Alright. I found the setting and am pretty confident you can edit the wiki now. 🤞

**Comment by PullJosh** [comment]
@micahlt Thanks for all your hard work on this! Documentation is super important but it isn't something I really want to work on right now, so your efforts are a huge help. 👍

**Comment by micahlt** [comment]
Sure!  I'm glad I can be of assistance.  I'd really like to see this
project though, but I'm not yet advanced enough in JS to be able to help
with the deeper code.  So docs are the next best thing!  😄👍

**Comment by PullJosh** [comment]
**Important update:** Documentation is now available at the [/docs page](https://scratch-js.now.sh/docs)!

There aren't any full tutorials up, but the documentation of all the blocks is enough that I'm satisfied for now. I'm going to close this issue until additional documentation becomes a clear priority again.

**Comment by nanaian** [comment]
_Wow_, that site looks amazing @PullJosh! ❤️ 
Hopefully the source is planned to go up at some point...? I see it's Now-backed, which is neat.

Small nit: The `loop x times` block is translated as `for (int i = 0; i < 10; i++) {`. That (`int`) isn't JS syntax! 😛

**Comment by PullJosh** [comment]
@nanaian Oops! Can you tell I've been writing some Java? :P (And yes, I plan to release the website source relatively soon. For now, it's easier to work on if I don't have to care about git stuff.)
