### ISSUE TITLE
"When I start as a clone" trigger has a one-frame delay

### ISSUE THREAD

**Issue by adroitwhiz** [PullJosh/scratch-js#24]
Currently, the scratch-js `Trigger.CLONE_START` triggers on the frame after "create clone" is called. In Scratch, it seems to be called immediately.

This manifests in the example project as clones appearing in their parent sprites' positions for one frame after they are created, which can be more easily seen by increasing their transparency:

![Peek 2019-12-28 11-20](https://user-images.githubusercontent.com/25993062/71546378-4045b500-2964-11ea-84bc-d554d0d46a2e.gif)

Compare this to [Scratch's behavior](https://scratch.mit.edu/projects/356389905/).

**Comment by PullJosh** [comment]
Wow! Interesting observation. I wonder if it applies to other Triggers fired from within a script (like broadcasts)...

**Comment by adroitwhiz** [comment]
Looks like it applies to broadcasts too (and possibly other Triggers).

If you run [this project](https://scratch.mit.edu/projects/356413944/) in scratch-js, Gobo lags behind Scratch Cat slightly. In Scratch, they are synchronized.

**Comment by adroitwhiz** [comment]
Although note that it sometimes [doesn't behave synchronously in other ways](https://scratch.mit.edu/projects/356487156/)... weird.
