### ISSUE TITLE
Rotation style API?

### ISSUE THREAD

**Issue by adroitwhiz** [PullJosh/scratch-js#27]
Scratch allows you to set a sprite's rotation style to "all around", "left-right", and "don't rotate".

I can think of two ways to implement this in scratch-js. One is to use string keys:

```js
this.rotationStyle = "all around";
this.rotationStyle = "left-right";
this.rotationStyle = "don't rotate"
```

The other is to use an enum:
```js
// these don't have to be Symbols; the important thing is they're stored in an enum
Sprite.RotationStyle = {
  AllAround: Symbol("all around"),
  LeftRight: Symbol("left-right"),
  DontRotate: Symbol("don't rotate")
}
```

which could be used like so:
```js
this.rotationStyle = Sprite.RotationStyle.AllAround;
this.rotationStyle = Sprite.RotationStyle.LeftRight;
this.rotationStyle = Sprite.RotationStyle.DontRotate;
```

I think the second option is less error-prone, but it would be the first time a static property is added to the `Sprite` class.

**Comment by PullJosh** [comment]
> I think the second option is less error-prone, but it would be the first time a static property is added to the `Sprite` class.

Sounds like it's time to break new ground! I'm in favor of the second option. :)

What do you think is the right time/place to add this feature? I see two reasonable options (*let me know if there are more!*):
1. Include rotation styles in the PR for the fancy new renderer
2. Merge the new renderer without this feature first and then add it after

**Comment by adroitwhiz** [comment]
It should be an easy feature to add, so I'll probably include it in the PR for the new renderer.
