### ISSUE TITLE
Support nested clones

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/scratch-js#28]
To match Scratch behavior, creating a clone of a clone currently does a sneaky bait-and-switch where the original sprite is cloned again instead.

As [pointed out](https://github.com/PullJosh/scratch-js/issues/25#issuecomment-569548874) by @nanaian, this is not very friendly to the honorable individuals who choose to use scratch-js.

A better option would be to store clone instances in a properly nested manner, but update sb-edit, the Scratch project translator, to always create a clone of the original when `create clone of [myself v]` is invoked. That would look like `this.sprites.sprite1.createClone()`.

**Comment by towerofnix** [comment]
>To match Scratch behavior, creating a clone of a clone currently does a sneaky bait-and-switch where the original sprite is cloned again instead.

I'm not sure if this is the case? :P I tried making a simple project where a clone creates a clone of itself, and it behaved as expected in 3.0 - check out [this project](https://scratch.mit.edu/projects/356491128/) (see the notes and credits). But in scratch-js, it - as you describe - clones the original sprite, thus not inheriting from its parent but the original, and this doesn't match the behavior in 3.0 (and previous versions of Scratch AFAIK).

**Comment by PullJosh** [comment]
Oh wow! You're right! I probably assumed Scratch's behavior without ever checking. 🤦‍♂ This definitely needs to change. And it should be pretty simple to do (tomorrow, when I'm not so tired...)

**Comment by towerofnix** [comment]
@PullJosh Mhmhm!! I think it only creates a clone of the original sprite if you specify the sprite's name -- "create clone of myself" always clones the acting target, not necessarily the original sprite.
