### ISSUE TITLE
Add package.json for dev dependencies

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/scratch-js#31]
See https://github.com/PullJosh/scratch-js/pull/29#issuecomment-569726096

Fancy development tools aren't strictly *required* to work on scratch-js, but eslint and prettier are both nice-to-haves. This can be indicated in the devDependencies of a package.json at the root.

While we're at it, there is also a vscode-specific file we can add to recommend certain vscode extensions for this editing repository (such as the prettier extension).

**Comment by nanaian** [comment]
While we're at it, an [editorconfig](https://editorconfig.org/) might be nice.

**Comment by PullJosh** [comment]
`package.json` asks for a license, and it would probably make sense to include a copy of one as a file in the repo.

I'm pretty much okay with "do whatever you want except sell this software". Anybody know which license will do that?

**Comment by adroitwhiz** [comment]
Do you want to allow people to e.g. make a game with `scratch-js` and sell the game, just not `scratch-js` itself?

There's a good summary of different licenses [here](https://choosealicense.com/licenses/).

**Comment by PullJosh** [comment]
Good point. I was thinking just scratch-js itself. If you write code that imports scratch-js, you can do with it whatever you please.

The more that I'm thinking about it, the more I think it makes sense to choose something simple and common like MIT. I don't want people to end up paying for scratch-js when it's available for free, but that seems highly unlikely anyway. A simple, clearly-permissive license should make it easy for

**Comment by PullJosh** [comment]
Fixed in #33
