### ISSUE TITLE
Support obsolete Scratch blocks

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/scratch-js#41]
Building off of #18 but I figure it makes sense to track these separately (requires more work in sb-edit than here, and not exactly part of the 'standardized' blocks of Scratch 3.0).

Some projects depend on obsolete Scratch blocks, such as "for each (variable) in (list)". In order to support all projects that can be run by Scratch 3.0, we should look into supporting such blocks — I'd be up for trying that out since I'd like to get familiar with the codebase anyway!

I believe we'd need to update sb-edit to support these blocks as well; most of them don't add any complex new behavior (and some just don't do *anything*, but still arguably oughtn't crash sb-edit), so most work would be tied to implementing their opcode/block definitions and writing export-related code in `toScratchJS.ts`.

I've got experience implementing most of these blocks - check it out: https://github.com/LLK/scratch-vm/issues/355#issuecomment-379399646. All those PRs are by me! :P

**Comment by towerofnix** [comment]
For bonus reference, here's @thisandagain's hacked block usage breakdown across all shared projects, from the comment below the one I linked:

![usage breakdown of hacked blocks; three columns: "opcode", "count", and "% of total". none of the blocks are used in more than 0.001% of all projects, and the count by block varies from ~1800 down to zero.](https://user-images.githubusercontent.com/747641/38449130-46ec7636-39d9-11e8-983d-762b7c2a3ff2.png)

And here's a hilariously big demo project containing dozens of hacked blocks: [link!](https://scratch.mit.edu/projects/56391904/) I certainly don't think it's a realistic target to support because it contains loads of blocks that just don't run or behave as blocks are supposed to at all; and of course it doesn't open in Scratch 3.0 either. But it is fun to look at ([in s2online](https://s2online.github.io/#56391904))! :P

**Comment by PullJosh** [comment]
This would be great! (And it's a nice low-risk way to get comfortable with the codebase.) 👍

**Comment by towerofnix** [comment]
:tada:! Work's begun here: https://github.com/PullJosh/sb-edit/compare/master...towerofnix:obsolete-blocks

**Comment by micahlt** [comment]
Yay!  I really need to get better at writing JS... I want to help too!  😺
