### ISSUE TITLE
Dev Discord or other chat?

### ISSUE THREAD

**Issue by adroitwhiz** [PullJosh/scratch-js#43]
Would it be worthwhile to create some sort of chat server (like Discord or perhaps Matrix) where scratch-js and other Scratch-related development projects could be discussed? Sorry if this doesn't really fit here, but I'm not sure where else to put this--Scratch doesn't allow people to share usernames for other platforms and GitHub has no messaging feature.

**Comment by PullJosh** [comment]
I think there's a lot of value in making all discussion public and preserved indefinitely. Chat is ephemeral, so there isn't any record of the decisions being made. I think GitHub issues are adequate as a discussion tool, with the nice benefit that everything is kept in one place.

And for the record, issues like this (that are just questions, not bugs/features) are not a problem. 👍

**Comment by towerofnix** [comment]
IMO I'm a little wary re: dev chats because I absolutely want the *vast* majority of discussion to happen in issues on GitHub, where they're clearly accessible to the public, and have clear organization so that it's easy for anyone to see the reasoning behind any change or suggestion.

That said I'm not opposed to the idea, as a general place to chat about and share other Scratch-related dev stuff, so long as when we decide it's worth investigating an idea for scratch-js/sb-edit, we do so primarily through issues, not dev chat.

(Oh hey, @PullJosh basically ninja'd me =P)

**Comment by adroitwhiz** [comment]
A more general place to talk about Scratch dev stuff is what I was originally envisioning. I agree that development decisions should be public, but it'd be a lot easier to talk about other stuff in a live-chat setting, which GitHub doesn't provide.

**Comment by PullJosh** [comment]
How about a Scratch forum post?

**Comment by towerofnix** [comment]
A forum thread on Scratch...that sort of reminds me of Snap<i>!</i>'s old threads, divided into a "user discussion" thread and "team discussion" thread, the former used for discussion and questions about Snap! itself and the latter used for development but also more lenient on going off/adjacent-topic, as a more casual discussion place.

I definitely liked that while it was going (it grew gradually less active and was closed earlier last year), but it basically functions the same as a less organized GitHub discussion thread - albeit more casual, but you get the same as well as live-chat capabilities from a Discord server. (Scratch is also a bit of a pain when it comes to sending messages reliably and inherently works like a forum moreso than a chat, so for casual discussion I feel Discord works better.)

**Comment by adroitwhiz** [comment]
I've gone ahead and set up a [Discord server](https://discord.gg/pcWeWpD) for "Scratch-adjacent" projects--feel free to join if you're interested in that sort of thing!

**Comment by towerofnix** [comment]
Aside: Another good reason for sharing a chat space is to have a place where we can talk about plans more casually, and we can more easily share basic progress - again, in a casual manner. So, if it's kept fairly active, you get a space that keeps building attention and interest in the project amongst the people working on it - which seems pretty valuable for making a large thing like scratch-js/sb-edit.

This is to say, @PullJosh, if you'd like, join us! There's a homepage now if you're curious :P
https://adjacent-topics.github.io/
