### ISSUE TITLE
Sprite.touching doesn't seem to work, at least in the demo

### ISSUE THREAD

**Issue by herohamp** [PullJosh/scratch-js#5]
In the demo you just fall continuously, this seems to be because `this.touching('Ground')` never returns to true, even after I disabled gravity and just moved into the black to the right, it still never returns true. This also happened regardless of whether or not fast collision is enabled.

**Comment by herohamp** [comment]
this seems to be because `this.touching('Ground')` never returns to true, even after I disabled gravity and just moved into the black to the right, it still never returns true.

**Comment by PullJosh** [comment]
That's odd. I just cloned a fresh copy of `master`, and everything works as expected. What's your browser/OS?

**Comment by PullJosh** [comment]
Just made a bunch of changes to the way the touching block works in #6. Would you be willing to `git pull` and try the new one out instead? Hopefully it'll fix the issue (despite not knowing the cause of the issue in the first place). :crossed_fingers:

**Comment by PullJosh** [comment]
Woah! It looks like there's a difference between `npm run watch` and `npm run build`. The first works; the second doesn't.

I have no idea why there would be any difference. :confused:

**Comment by herohamp** [comment]
I just retested, it has to the with the --mode=production, when I switched it to --mode=development it started working

**Comment by PullJosh** [comment]
Ah! Looks like there's some code that relies on `sprite.constructor.name` to check which type of sprite it is. In production mode, webpack shortens the names of everything to be as small as possible. Thus, the check doesn't work.

I should have known better than to rely on that type of thing... Give me a few minutes.

**Comment by PullJosh** [comment]
Should be all fixed now. `git pull` and give it another try. ;)

**Comment by herohamp** [comment]
Still doesnt work with the production tag

**Comment by PullJosh** [comment]
Odd. Hopefully you're pulling from the master branch. Would you be willing to double-check that you actually have the latest code? Look in the `touching` function (line 80) in `[git repo]/scratch-js/Sprite.js`. The second line should say... 
```js
// We want this (new)
const matching = spr => spr.name === sprName
```
as opposed to...
```js
// Not this (old)
const matching = spr => spr.constructor.name === sprName
```
Which one do you have?

**Comment by herohamp** [comment]
https://i.imgur.com/HKfpF6h.png, yeah I have the new code, this is so strange

**Comment by PullJosh** [comment]
That's crazy! You also have the other changes from e5a5dd5, right? If `Ground.js` or `Player.js` are missing the new `this.name` lines, you would get the same falling through the ground effect.

I'm completely confident that the code works, as long as you have it all. I was able to replicate your issue and solve it with 100% consistency. My only other idea is some sort of caching problem either in the browser or in webpack itself.

**Comment by herohamp** [comment]
Ok, I just redeleted everything and git cloned, and now it works. That was so strange.

**Comment by PullJosh** [comment]
Okay! That was odd, but I'm glad it's taken care of now. :smile:
