### ISSUE TITLE
Implement audio effects

### ISSUE THREAD

**Issue by towerofnix** [PullJosh/scratch-js#53]
Branching off of #18 and building on my work in #52 and various PRs implementing or updating blocks, I'd like to personally work on implementing audio effects. Here's the todo list:

- [x] Get #52 merged, since this builds off of it
- [x] Volume
- [x] Pan left/right
- [x] Pitch
- [x] APIs associated with these: `this.setAudioEffect("pan", 50)` for instance (I'm considering putting volume in the same API as other audio effects, to keep things simple)
- [x] "Clear audio effects" block
- [x] Clear audio effects once project starts (correctly)
- [x] Make sure clones inherit effects properly
- [x] Share effect nodes for all sounds in a target, instead of storing distinct but equal instances per sound
- [x] Clamping for volume and pan (I believe pitch isn't clamped)
- [x] Number casting / don't do anything for non-numbers
- [x] Discard effect nodes when equal to initial value (to save memory/processing)

Implementing all of this would, in combination with #52, complete support for sound compatibility between Scratch 3.0 and scratch-js (excluding the Instruments extension).

I'd study and implement code as identical as possible to the behavior covered in the ["effects"](https://github.com/LLK/scratch-audio/tree/develop/src/effects) directory of scratch-audio, the engine built for playing sound in Scratch.

(An alternative route to this goal would be implementing the scratch-audio library itself into scratch-js, but scratch-js as of yet has no dependencies. Also, we implement our own rendering system rather than using scratch-render—our rendering system was made by @adroitwhiz, who's very knowledgeable of Scratch 3.0's rendering—so it would make sense to do the same for audio.)

/cc @PullJosh - Does this sound like a good plan to you? Also, I don't know if it's possible to assign an issue to a non-collaborator; if so, I'd appreciate the assignment, so that the issue list is kept organized.

**Comment by PullJosh** [comment]
Sounds excellent! (Dependency-free is the way to go.) Best of luck, and let me know if I can be of any assistance. :)

**Comment by towerofnix** [comment]
Complete as of #54 being merged! 🚀
