### ISSUE TITLE
User Report: Sprites half-size on Mac (Chrome)

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/scratch-js#61]
https://scratch.mit.edu/projects/345789566/#comments-130544364

> Okay, On chrome on my mac: Sprites shrink down to the bottom left corner of the display box, a quarter of the size. Pen covers the entire screen, however. keyboard scroll controls are not locked. Although you may be aware of some of these.

> On further inspection, some projects have improperly displayed sprites than others for some reason

> Here's what I tested: https://scratch-js.now.sh/?id=382544425 , https://scratch-js.now.sh/?id=380380623

Not sure if this is an issue with scratch-js or sb-edit.

**Comment by adroitwhiz** [comment]
You can reproduce this using the dev tools' "responsive design mode" with a device pixel ratio > 1. Seems to be an issue with the GL viewport. I'll have a look.
