### ISSUE TITLE
Green Flag doesn't reset

### ISSUE THREAD

**Issue by Wetbikeboy2500** [PullJosh/scratch-js#7]
When the green flag button is clicked it doesn't reset the sprite to where it should begin on the stage. A refresh is required in order to reset the project.

**Comment by herohamp** [comment]
Infact if you spam refresh on the demo, it will run faster because all the code is being executed multiple times

**Comment by Wetbikeboy2500** [comment]
Also with the latest demo, the stage resets, but the sound doesn't and begins to overlap.

**Comment by PullJosh** [comment]
This should all be resolved in d415d1d74b0b4516bd827a87499f7b1306d595f8. Running scripts are cancelled when called again, and sounds stop when the green flag is clicked.

Let me know if you still have issues!
